name: Test Docker tag

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run on branch
        id: tag_branch
        if: startsWith(github.ref, 'refs/heads') == true
        uses: "./docker-tag/"
      - name: Test on branch
        if: startsWith(github.ref, 'refs/heads') == true
        run: |
          echo "${{steps.tag_branch.outputs.tag}}"
      - name: Run on tag without replacement
        id: tag_without
        if: startsWith(github.ref, 'refs/tags') == true
        uses: "./docker-tag/"
      - name: Test on tag without replacement
        if: startsWith(github.ref, 'refs/tags') == true
        run: |
          echo "${{steps.tag_without.outputs.tag}}"
      - name: Run on tag with replacement
        id: tag_with
        if: startsWith(github.ref, 'refs/tags') == true
        uses: "./docker-tag/"
        with:
          tag_replace_pattern: "v"
      - name: Test on tag with replacement
        if: startsWith(github.ref, 'refs/tags') == true
        run: |
          echo "${{steps.tag_with.outputs.tag}}"
